stages:
  - update-repo

update-repo:
  stage: update-repo
  only:
    - master
  script:
    - whoami
    - pwd
    - cd /home/ubuntu/durations-for-todoist
    - git pull origin master
    - ~/run-durations.sh &
